### PR TITLE
For whole file mode, return an Enumerator of lines instead of an Array

### PR DESCRIPTION
**Pull request by cmdicely**
Avoids eager loading the whole input stream before processing; makes working with large streams line-by-line more responsive (and faster in total, if the whole stream isn't needed, such as when using #take.)

### CODE REVIEW

**Comment by thisredone** [comment]
I'm not sure about this. It's slightly more confusing because some things aren't the same as with the arrays. I do understand where you're coming from though and would like this to be an option. Another switch like `-e` for Enumerator could be used but that's also bumping the complexity somewhat.

**Comment by marius** [comment]
Could you elaborate on "aren't the same as with arrays"?

**Comment by thisredone** [comment]
Well for one things like `#last` aren't there. `#size` returns `nil` and you gotta remember to use `#count` instead

**Comment by cmdicely** [comment]
I think where it makes a difference, Enumerator is usually going to be what is wanted, but I can see that there will be times when you really want Array.

With a bit more line count, it would be possible to have it use something that was lazy like Enumerator but also supports the extra Array methods by forcing the creation of an Array if they are called.

**Comment by pvdb** [comment]
I appreciate the arguments both ways, but on balance I personally favour the `Enumerator` approach over the `Array` one _(together with the other 5 people who upvoted it so far)_ :smiley:

Ingesting the entire input stream before starting any processing is - like @cmdicely already mentioned - a considerable overhead _(especially if you don't actually process it in its entirety)_ and also causes unnecessary memory bloat _(as the entire input stream is read into memory)_.

Ingesting the entire input stream also causes issues with **slow** input streams, not even **large** ones, e.g. when retrieving things over the network... consider the difference:

#### using the `Array` approach

```
$ (echo foo &; sleep 5 && echo bar; ) | time rb 'take(1).map(&:upcase)'
FOO
rb 'take(1).map(&:upcase)'  0.24s user 0.09s system 6% cpu 5.081 total
$ _
```

#### using the `Enumerator` approach

```
$ (echo foo &; sleep 5 && echo bar; ) | time rb 'take(1).map(&:upcase)'
FOO
rb 'take(1).map(&:upcase)'  0.23s user 0.09s system 88% cpu 0.357 total
$ _
```

The first approach unnecessarily waits the full 5 seconds before finishing _(and has to)_ whereas the lazy enumerator doesn't... it finishes as soon as it can.

I appreciate @thisredone's argument that _"some things aren't the same as with the arrays"_, but that's easily resolved IMO: if you need array behaviour, you just call `to_a` on the enumerator...

```
$ ( echo foo; echo bar; ) | rb to_a.last.upcase
BAR
$ _
```

The thing I like about this approach is that the decision to "take the hit" of ingesting the entire input stream is explicitly made by the user of `rb`, instead of being forced upon them by the utility... and it does it without the additional complexity of introducing an extra `-e` command line option.

Thoughts?

**Comment by thisredone** [comment]
I'm convinced!

**Pull request merged**
